format = "$time$directory$git_branch$git_state$git_status$character"
add_newline = false

[directory]
style = "blue"

[character]
symbol = ">"

[git_branch]
symbol = ""

[time]
disabled = false
format = "[\\[$time\\]]($style) "
time_format = "%H:%M"
