add_newline = false
prompt_order=["time", "directory", "git_branch", "git_state", "git_status", "character"]

[directory]
style = "blue"

[line_break]
disabled = true

[character]
symbol = ">"

[git_branch]
symbol = ""

[nodejs]
disabled = true

[package]
disabled = true

[time]
disabled = false
format = "[%H:%M]"
